### ISSUE TITLE
please submit pluto support upstream

### ISSUE THREAD

**Issue by ZeroChaos-** [csete/gr-osmosdr-gqrx#10]
upstream seems to have no intention of ever writing support for the default pluto firmware, while you already have.  it would be great to get this upstreamed so people can use their plutosdr without building a custom gr-osmosdr

**Comment by csete** [comment]
Already tried when I wrote it.

**Comment by ZeroChaos-** [comment]
Any specific reason they rejected it? It seems to work rather well.

**Comment by ZeroChaos-** [comment]
please forgive using this bug tracker for contact, but...

No longer work on gqrx?  I'm very sorry to hear that.  Can you please put something on the website or something to say that it's abandoned?  You have done such a great job with it I'm afraid no one will even try to pick it up if you don't explicitly say you aren't going to work on it anymore.

**Comment by csete** [comment]
Can you please stop asking me to do things that I do not want to spend time on ;-)

There is a difference between "no longer work on it" and abandoned. There is an effort being put into finding a new maintainer(s) and I am still very responsive both on GitHub and on the mailing list. There is no need to panic. It still works and it is still usable; I just no longer worry about driver issues or whether it works on the hundreds of combinations of operating systems and architectures, which used to take 90% of my gqrx time.

**Comment by csete** [comment]
> Can you please stop asking me to do things that I do not want to spend time on ;-)

Sorry, it was just a bad joke, but the rest of the reasoning remains.

**Comment by ZeroChaos-** [comment]
thanks for clearing that up :-)  I'll breathe a little easier for now.
