### ISSUE TITLE
10 MHz AirSpyMini

### ISSUE THREAD

**Issue by LumRCA** [csete/gr-osmosdr-gqrx#12]
Good day. This layer do not allow me set 10 MHz sample rate in AirSpy Mini. But original gr-osmosdr allow me set this sample rate.
I would be glad if something could help.

**Comment by csete** [comment]
Hi,

I see no difference between the lib/airspy/airspy_source_c.cc of this repository and the one from https://osmocom.org/projects/gr-osmosdr/wiki so what you call original must be something you patched yourself.

Please understand that the only purpose with this repository is to make my **patches** available, not to provide an alternative source for gr-osmosdr.
