### ISSUE TITLE
Doesn't buit with rtl-sdr support

### ISSUE THREAD

**Issue by bogdanr** [csete/gr-osmosdr-gqrx#2]
Hello,

When I am trying to build this with rtl-sdr support I get the following error:
```
/root/gr-osmosdr-gqrx/lib/rtl/rtl_source_c.cc: In constructor 'rtl_source_c::rtl_source_c(const string&)':
/root/gr-osmosdr-gqrx/lib/rtl/rtl_source_c.cc:224:9: error: 'rtlsdr_set_bias_tee' was not declared in this scope
   ret = rtlsdr_set_bias_tee(_dev, bias_tee);
         ^~~~~~~~~~~~~~~~~~~
/root/gr-osmosdr-gqrx/lib/rtl/rtl_source_c.cc:224:9: note: suggested alternative: 'rtlsdr_set_xtal_freq'
   ret = rtlsdr_set_bias_tee(_dev, bias_tee);
         ^~~~~~~~~~~~~~~~~~~
         rtlsdr_set_xtal_freq
```

**Comment by csete** [comment]
You have to use the latest librtlsdr from their git repository.

Please do not report bugs here unless they are directly related to the patches that are not yet merged upstream. This is NOT the gr-osmosdr repository. It is only my own staging area that I use for packing gqrx releases with patches that are not yet available upstream.
