### ISSUE TITLE
rtl_tcp_source_c.cc:301:9: error: expected expression

### ISSUE THREAD

**Issue by drom** [csete/gr-osmosdr-gqrx#5]
I am trying to build `plutosdr` branch of the package on OpenSuSe Tumbleweed and getting this error:
```
[  6%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/rtl_tcp/rtl_tcp_source_c.cc.o
/home/drom/work/github/csete/gr-osmosdr-gqrx/lib/rtl_tcp/rtl_tcp_source_c.cc:301:9: error: expected expression
  cmd = { 0x09, htonl(direct_samp) };
        ^
/home/drom/work/github/csete/gr-osmosdr-gqrx/lib/rtl_tcp/rtl_tcp_source_c.cc:307:9: error: expected expression
  cmd = { 0x0a, htonl(offset_tune) };
        ^
/home/drom/work/github/csete/gr-osmosdr-gqrx/lib/rtl_tcp/rtl_tcp_source_c.cc:311:9: error: expected expression
  cmd = { 0x0e, htonl(bias_tee) };
        ^
/home/drom/work/github/csete/gr-osmosdr-gqrx/lib/rtl_tcp/rtl_tcp_source_c.cc:570:9: error: expected expression
  cmd = { 0x08, htonl(automatic) };
        ^
```

**Comment by csete** [comment]
Hi @drom 

I doubt that my plutosdr branch has anything to do with these errors, so please make sure that you can build the master branch and/or the [official gr-osmosdr ](https://osmocom.org/projects/sdr/wiki/GrOsmoSDR) code before trying my branches or reporting bugs here.

Like I said many times before, this is not an official gr-osmosdr repository and certainly no support forum. It is used to host my patches that have not yet been merged into the official repository. Reporting problems not directly related to my changes is a waste of time.

**Comment by drom** [comment]
Thank you @csete . You are right. I will try building official master.
Just got my Pluto box and try running it with my favorite GQRX.
