### ISSUE TITLE
Compile of plutosdr branch fails on Ubuntu 17.10, decimation removed in gr-iio

### ISSUE THREAD

**Issue by papavictor** [csete/gr-osmosdr-gqrx#7]
See https://github.com/analogdevicesinc/gr-iio/commit/1e7bad085fd427f090eb02fe7cdcbfdabf2ea13c#diff-60e02af80741bf78dbc29cada52fecbe

When compiling, I get the following error:

gr-osmosdr-gqrx-plutosdr/lib/plutosdr/plutosdr_source_c.cc: In constructor ‘plutosdr_source_c::plutosdr_source_c(const string&)’:
gr-osmosdr-gqrx-plutosdr/lib/plutosdr/plutosdr_source_c.cc:63:65: error: no matching function for call to ‘gr::iio::pluto_source::make(const char*, long long unsigned int&, long unsigned int&, long unsigned int&, long unsigned int&, long unsigned int&, bool&, bool&, bool&, const char [7], double&, const char*, bool&)’
                                      filter.c_str(), filter_auto);
                                                                 ^
In file included from gr-osmosdr-gqrx-plutosdr/lib/plutosdr/plutosdr_source_c.h:26:0,
                 from gr-osmosdr-gqrx-plutosdr/lib/plutosdr/plutosdr_source_c.cc:25:
/usr/include/gnuradio/iio/pluto_source.h:41:15: note: candidate: static gr::iio::pluto_source::sptr gr::iio::pluto_source::make(const string&, long long unsigned int, long unsigned int, long unsigned int, long unsigned int, bool, bool, bool, const char*, double, const char*, bool)
   static sptr make(const std::string &uri,
               ^~~~
/usr/include/gnuradio/iio/pluto_source.h:41:15: note:   **candidate expects 12 arguments, 13 provided**
lib/CMakeFiles/gnuradio-osmosdr.dir/build.make:326: recipe for target 'lib/CMakeFiles/gnuradio-osmosdr.dir/plutosdr/plutosdr_source_c.cc.o' failed

Seems to be the 'decimation' int in this code block, which was removed upstream in December:

```
  _src = gr::iio::pluto_source::make(uri.c_str(), frequency, samplerate,
                                     decimation, bandwidth, buffer_size,
                                     quadrature, rfdc, bbdc,
                                     "manual", gain_value,
                                     filter.c_str(), filter_auto);
```

Looks like this is not used further upstream in the filter: https://github.com/analogdevicesinc/gr-iio/issues/7

**Comment by csete** [comment]
I am aware of the issue but I do not have the time to do the repackaging right now. I suppose you can just remove the parameter in your local build?

**Comment by csete** [comment]
Updated.
